In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
import math
from sklearn.metrics import mean_squared_error,mean_absolute_error
import numpy.linalg as la
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import TruncatedSVD
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

In [ ]:
path = "/content/drive/Shareddrives/DATA 270/data_270_dataset.csv"
df = pd.read_csv(path)

In [ ]:
df.head()

,Solar Radiation Average,Average Soil Temperature,Maximum Air Temperature,Average Vapor Pressure,Average Wind Speed,Precipitation,Maximum Relative Humidity,Dew Point,month,year,county_encoded,week,DSCI,class
0,134.750000,47.950000,57.275000,8.300000,0.0,0.0,92.500000,39.550000,1,2000,0.0,1,61,0.0
1,112.857143,50.271429,58.571429,9.557143,0.0,0.0,92.000000,42.414286,1,2000,0.0,2,50,0.0
2,105.428571,52.342857,60.757143,10.957143,0.0,0.0,96.857143,46.828571,1,2000,0.0,3,0,0.0
3,86.571429,55.185714,59.871429,12.957143,0.0,0.0,98.142857,51.257143,1,2000,0.0,4,0,0.0
4,154.857143,53.242857,60.957143,9.942857,0.0,0.0,93.142857,44.228571,2,2000,0.0,5,0,0.0

In [ ]:
train = df[df['year'] <= 2017]
test = df[df['year'] >= 2018]
n_train = train.shape
n_test = test.shape
n_train[0], n_test[0]

(39937, 6907)

In [ ]:
train = train.drop(['year','DSCI','Average Wind Speed'],axis=1)
test = test.drop(['year','DSCI','Average Wind Speed'],axis=1)

In [ ]:
train.head()

,Solar Radiation Average,Average Soil Temperature,Maximum Air Temperature,Average Vapor Pressure,Precipitation,Maximum Relative Humidity,Dew Point,month,county_encoded,week,class
0,134.750000,47.950000,57.275000,8.300000,0.0,92.500000,39.550000,1,0.0,1,0.0
1,112.857143,50.271429,58.571429,9.557143,0.0,92.000000,42.414286,1,0.0,2,0.0
2,105.428571,52.342857,60.757143,10.957143,0.0,96.857143,46.828571,1,0.0,3,0.0
3,86.571429,55.185714,59.871429,12.957143,0.0,98.142857,51.257143,1,0.0,4,0.0
4,154.857143,53.242857,60.957143,9.942857,0.0,93.142857,44.228571,2,0.0,5,0.0

In [ ]:
X_train= train.drop(['class',],axis=1)
y_train= train['class']
X_test = test.drop(['class'],axis=1)
y_test = test['class']

In [ ]:
X_train.head()

,Solar Radiation Average,Average Soil Temperature,Maximum Air Temperature,Average Vapor Pressure,Precipitation,Maximum Relative Humidity,Dew Point,month,county_encoded,week
0,134.750000,47.950000,57.275000,8.300000,0.0,92.500000,39.550000,1,0.0,1
1,112.857143,50.271429,58.571429,9.557143,0.0,92.000000,42.414286,1,0.0,2
2,105.428571,52.342857,60.757143,10.957143,0.0,96.857143,46.828571,1,0.0,3
3,86.571429,55.185714,59.871429,12.957143,0.0,98.142857,51.257143,1,0.0,4
4,154.857143,53.242857,60.957143,9.942857,0.0,93.142857,44.228571,2,0.0,5

In [ ]:
sc = StandardScaler()
X_scaled = sc.fit_transform(X_train)

svd = TruncatedSVD(n_components=4, algorithm='randomized',
                   random_state=0)
X_svd_train = svd.fit_transform(X_scaled)

In [ ]:
dfx_trans = pd.DataFrame(data=X_scaled,)
dfx_trans.head()

,0,1,2,3,4,5,6,7,8,9
0,-1.582928,-1.271001,-1.144010,-0.475835,-0.445007,0.606219,-0.558445,-1.604049,-1.810119,-1.702230
1,-1.702570,-1.057629,-1.049323,-0.239247,-0.445007,0.562057,-0.248480,-1.604049,-1.810119,-1.635828
2,-1.743166,-0.867235,-0.889686,0.024226,-0.445007,0.991061,0.229221,-1.604049,-1.810119,-1.569426
3,-1.846218,-0.605935,-0.954375,0.400616,-0.445007,1.104621,0.708467,-1.604049,-1.810119,-1.503023
4,-1.473045,-0.784512,-0.875079,-0.166657,-0.445007,0.662999,-0.052144,-1.313951,-1.810119,-1.436621

In [ ]:
sc = StandardScaler()
scaled = sc.fit_transform(X_test)

svd = TruncatedSVD(n_components=4, algorithm='randomized',
                   random_state=0)
X_svd_test = svd.fit_transform(scaled)

In [ ]:
pca = PCA(n_components=4)
X_pca = pca.fit(X_train)
X_pca_train = pca.transform(X_train)

In [ ]:
pca = PCA(n_components=4)
X_pca = pca.fit(X_test)
X_pca_test = pca.transform(X_test)

In [ ]:
def randomf(X_train,X_test,y_train,y_test):
  rf = RandomForestClassifier()
  rf.fit(X_train, y_train)
  y_pred = rf.predict(X_test)
  test_acc = accuracy_score(y_pred,y_test)

  y_ptrain = rf.predict(X_train)
  train_acc = accuracy_score(y_ptrain,y_train)
  
  return test_acc, train_acc

def knn(X_train,X_test,y_train,y_test):
  knn = KNeighborsClassifier()
  knn.fit(X_train, y_train)
  y_pred = knn.predict(X_test)
  test_acc = accuracy_score(y_pred,y_test)

  y_ptrain = knn.predict(X_train)
  train_acc = accuracy_score(y_ptrain,y_train)
  
  return test_acc, train_acc

In [ ]:
print(randomf(X_train,X_test,y_train,y_test))   (0.6749674243521065, 0.7351578736510003)

(0.7175329375995367, 1.0)
(0.6749674243521065, 0.7351578736510003)

In [ ]:
from sklearn.metrics import accuracy_score, matthews_corrcoef, log_loss, f1_score

from sklearn.metrics import precision_score,recall_score

In [ ]:
test_acc = accuracy_score(y_pred, y_test)
rec_score =recall_score(y_test, y_pred, average='macro')
prec_score = precision_score(y_test, y_pred, average='macro')         
test_f1 = f1_score(y_pred,y_test,average='macro')
print('RF Accuracy       :',test_acc)
print('RF Precision Score:',prec_score)
print('RF Accuracy       :',rec_score)
print('RF F1 Score       :',test_f1)

RF Accuracy       : 0.715
RF Precision Score: 0.708
RF Recall         : 0.698
RF F1 Score       : 0.7